services:
    crimson-server:
        image: crimson-server
        container_name: crimson-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - .env
        restart: unless-stopped
