services:
    crimson-server:
        image: tabishnaqvi1311/crimson-server:latest
        container_name: crimson-server
        ports:
            - "8080:8080"
        env_file:
            - .env
        restart: always
