name: deploy

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      tabishnaqvi1311/crimson-server:latest
                      tabishnaqvi1311/crimson-server:${{ github.sha }}

            - name: deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_HOST }}
                  username: ${{ secrets.DO_USERNAME }}
                  key: ${{ secrets.DO_SSH_KEY }}
                  script: |
                      set -e
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd /home/tabish/crimson-server
                      docker pull tabishnaqvi1311/crimson-server:latest
                      docker-compose down
                      docker-compose up -d
                      echo "deployment success!"
