name: dev

on:
    push:
        branches: ["dev"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.13.0"

            - name: install deps
              run: |
                  npm install
                  npm run compile
                  npx prisma generate
                  echo "deps installed"

            - name: build image
              run: |
                  docker build -t crimson-server .

            - name: run container
              run: |
                  docker compose up -d

            - name: stop and remove container
              if: always()
              run: docker compose down

            - name: finalize dev checks
              run: echo "dev lgtm!"
